### ISSUE TITLE
versatiles-rs with frontend (Brotli) produce DOMException on client site

### ISSUE THREAD

**Issue by IT-Experte** [versatiles-org/versatiles-rs#112]
I getting different errors with self hostet versatiles-rs (v0.12.6) with Brotli packed frontend.

- Firefox 130:
DOMException: An attempt was made to use an object that is not, or is no longer, usable evented.ts:149:20

- Google Chrome 129: 
ajax.ts:158 - GET http://10.10.1.15:80/assets/sprites/sprites.png net::ERR_CONTENT_DECODING_FAILED
evented.ts:149 TypeError: Failed to fetch

---
I have started versatiles-rs with frontend (Brotli).

`versatiles server -p 80 -s '/opt/frontend.br.tar' '/opt/osm.versatiles'`

Using the frontend with Tar.gz produces no errors.

`versatiles server -p 80 -s '/opt/frontend.tar.gz' '/opt/osm.versatiles'`

If you can't reproduce the error, ask me.

**Comment by MichaelKreil** [comment]
That's strange. *head scratching*
I also have Versatiles v0.12.6, the frontend (v2.0.5), Google v129 and Firefox v120 and it works fine for me.
Do you have any idea how I could reproduce this? Can you send me a public URL, for example?

**Comment by IT-Experte** [comment]
This example [URL](http://212.227.64.221:8000) is run as docker container (Versatiles v0.12.6) with [Frontend](https://github.com/versatiles-org/versatiles-frontend/releases/download/v2.0.5/frontend.br.tar) 2.0.5 (Brotli).

versatiles server -p 8000 -s /mnt/frontend.br.tar /mnt/osm.versatiles

Error from Firefox:

![grafik](https://github.com/user-attachments/assets/1dda123f-3cc9-4a71-9d02-22047c2daaa2)

Error from Google Chrome:

![grafik](https://github.com/user-attachments/assets/27e33047-81dc-49f1-86d5-3c8f2bf73c27)

Maybe the connection is closed too fast with Brolti ?

**Comment by MichaelKreil** [comment]
One thing I noticed is that the response is always Brotli-compressed, even if the browser doesn't want that.
```bash
$ curl -vH 'Accept-encoding: gzip' "http://localhost:80/assets/sprites/sprites@2x.png" > /dev/null
...
> Accept-encoding: gzip
...
< HTTP/1.1 200 OK
< content-type: image/png
< cache-control: public, max-age=2419200, no-transform
< vary: accept-encoding
< access-control-allow-origin: *
< content-encoding: br
< content-length: 133116
```

OK, I'll have to look into that.
Maybe a fix will also fix the other issues.

**Comment by MichaelKreil** [comment]
0.12.8 has been released. Can you please check whether the issue has been resolved?

**Comment by IT-Experte** [comment]
Now it also works with Brotli. Great job. Thanks a lot.
