### ISSUE TITLE
Logging server requests in verbose mode

### ISSUE THREAD

**Issue by IT-Experte** [versatiles-org/versatiles-rs#113]
Logging every HTTP request into console output would help debugging.

Currently no output is generated in server mode with the verbose option.

`versatiles serve --verbose --port 80 -s frontend.tar.gz osm.versatiles`

**Comment by MichaelKreil** [comment]
I have added more logging in v0.12.7. The new release will be available in a few minutes.
Use the flag ‘-vvvv’ to get the full power of maximum verbosity. :)
Does this help you?

**Comment by IT-Experte** [comment]
Yes, works well and helps a lot. Can you add the -vvvv option to the program help?
