### ISSUE TITLE
Spread-out data points lead to error in mbtiles reader

### ISSUE THREAD

**Issue by sastcsgh** [versatiles-org/versatiles-rs#117]
Hi all, 

While trying to convert a rather sparse .mbtiles file, I ran into the following error. 
Invalid column type Null at index: 0, name: MIN(tile_row)

I traced this error back to [/versatiles_container/src/container/mbtiles/reader.rs](https://github.com/versatiles-org/versatiles-rs/blob/main/versatiles_container/src/container/mbtiles/reader.rs#L208-L241), where it goes through the zoom levels and finds the middle column and calculates the minimum and maximum tile_row value. However - this middle column is not guaranteed to have data associated with it. Case in point, in my dataset at zoom level 3 I have data in column 2 and 4, so the calculated middle column value is 3, which has no data, so the min(tile_row) is NULL. 

I guess there should be some check in place here if there actually is data for this middle column value, and if not take the closest value that exists. (Edit: alternatively, of course, you could just take one of the columns that you already know have data in them, that might be faster, since we don't know how the data is distributed anyway. I just tested this locally, seems to work fine.)

**Comment by MichaelKreil** [comment]
Good point!
Finding the middle column was a hack to speed up the SQL queries ... but yes, this hack doesn't seem to be a good solution, because there might not be a "middle column". :(
What do you think about using the minimum column: be80b611cd4a2056ef4fb82ebbc6cf345b041fc1 ?

**Comment by sastcsgh** [comment]
Yeah, that was the way I tested it locally as well. Works fine for me! 

(The exact effect it has on the speed is probably dependent on the distribution of the data, and for most distributions the center is probably a good place to look - so one could try that and fall back to the first column only if it doesn't work, but I'm not sure it makes that much of a difference speedwise)

**Comment by MichaelKreil** [comment]
I assume that in most cases the tiles are arranged in a rectangle. In these cases, it doesn't matter which column is selected.
In all other cases, the query may take a second, but I think that's tolerable.

I'll trigger a new release.
