### ISSUE TITLE
Bug in pmtiles reader: zoom level 0 disregarded

### ISSUE THREAD

**Issue by sastcsgh** [versatiles-org/versatiles-rs#122]
Hi all, 
Think I found another bug. When I convert a pmtiles file to the versatiles container format, zoom level 0 is not retained. The same happens when I probe a .pmtiles container that I know contains a zoom level 0. 
I'm not sure, but I think it may have something to do with [this line](https://github.com/versatiles-org/versatiles-rs/blob/e9e308f69b0c4bb3ad711308cfbf57028028388c/versatiles_container/src/container/pmtiles/reader.rs#L164C6-L164C44).

**Comment by MichaelKreil** [comment]
Many thanks!
