### ISSUE TITLE
Issue with Geofabrik tiles

### ISSUE THREAD

**Issue by ThomasG77** [versatiles-org/versatiles-rs#17]
I've tried using versatiles 0.2.14 latest version with tiles provided at https://blog.geofabrik.de/?p=589 and got some issues.

They are mentioned at https://gist.github.com/ThomasG77/7d99b7d79138bda9a2dfb092728da54c
I can open dedicated issues more focused if you confirm you have the same issues as in the gist recipe.

**Comment by MichaelKreil** [comment]
I am currently reviewing and testing the code of version 0.2.14 and have already found a lot of bugs. I might have a release candidate in the next few days.
But it is a good idea to use the mbtiles from the GeoFactory for testing!
When I think that versatiles is stable enough and can handle other mbtiles without problems, I'll come back to your issue.

**Comment by MichaelKreil** [comment]
I believe I have fixed the issue. There were two problems that I identified:

1. The tar file from Geofabrik contains tiles with the file extension ".pbf," but they are actually gzipped and should have the extension ".pbf.gz." To address this, I have introduced a new argument called "--override-input-compression" which allows you to manually override the compression type and set it to "gzip."

2. The files within the tar archive are organized as z/y/x, whereas they should be organized as z/x/y. To resolve this, I have added another new argument called "--swap-xy."

Version 0.5.0 implements these two arguments.

To test the solution directly with the tar file:
```bash
versatiles serve -s ./frontend.br.tar -p 8080 test.tar --override-input-compression gzip --swap-xy
```

Or you can convert the tar file to the faster versatiles format:
```bash
versatiles convert test.tar test.versatiles --override-input-compression gzip --swap-xy
versatiles serve -s ./frontend.br.tar -p 8080 test.versatiles
```
