### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by yetzt** [versatiles-org/versatiles-rs#30]
I'd like to `brew install versatiles`

**Comment by MichaelKreil** [comment]
Formulas like [rustfmt](https://formulae.brew.sh/formula/rustfmt), [mdcat](https://formulae.brew.sh/formula/mdcat), [jrsonnet](https://formulae.brew.sh/formula/jrsonnet), [tinysearch](https://formulae.brew.sh/formula/tinysearch) or [tealdeer](https://formulae.brew.sh/formula/tealdeer) implemented build and release workflows. The urls of the release files are then used for homebrew.

There are also some articles about Rust projects on Homebrew like: [1](https://dev.to/superfola/making-your-project-available-through-homebrew-1ll5), [2](https://federicoterzi.com/blog/how-to-publish-your-rust-project-on-homebrew/), [3](https://kawamurakazushi.com/20200217-publishing-a-rust-cli-to-Homebrew/), [4](https://skerritt.blog/packaging-your-rust-code/)

**Comment by MichaelKreil** [comment]
Ok, I managed to write a GitHub Action that automatically creates binaries for Linux (x86) and Mac (x86+ARM) and adds them to the latest release:
https://github.com/versatiles-org/versatiles-rs/releases/tag/v0.5.6
Could you figure out how to add them to Homebrew, @yetzt ?

**Comment by yetzt** [comment]
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by MichaelKreil** [comment]
@yetzt can you verify that this binary runs on a Mac with an ARM processor?
https://github.com/versatiles-org/versatiles-rs/releases/download/v0.5.7/versatiles-macos-aarch64.tar.gz

**Comment by yetzt** [comment]
macos is complaining about it not being signed, but it runs fine.

**Comment by MichaelKreil** [comment]
done ✅
```bash
brew tap versatiles-org/versatiles
brew install versatiles
```
