### ISSUE TITLE
does not compile under windows

### ISSUE THREAD

**Issue by MichaelKreil** [versatiles-org/versatiles-rs#31]
Multiple errors, e.g:

error[E0433]: failed to resolve: could not find `unix` in `os`
 --> src\containers\tar\reader.rs:9:78
... collections::HashMap, env::current_dir, fmt::Debug, fs::File, io::Read, os::unix::prelude::FileExt, path::Path,

**Comment by inasis** [comment]
Fixed a bug in the code that occurred during compilation.

I attempted to compile it on Microsoft Windows 10 Home x86/64 10.0.19045, using cargo 1.80.0 (376290515 2024-07-16) and
Linux 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux, using cargo 1.80.0 (376290515 2024-07-16)

**Comment by MichaelKreil** [comment]
Hooray, it works beautifully!
I've also fixed some tests (for Windows), but now we have a CI that builds and tests for Linux and Windows, e.g.: https://github.com/versatiles-org/versatiles-rs/actions/runs/10290513275
VersaTiles is now also built and released for Windows (Intel+ARM): https://github.com/versatiles-org/versatiles-rs/releases/tag/v0.12.5
Thank you very much!
