### ISSUE TITLE
Blank space with local converted versatiles file

### ISSUE THREAD

**Issue by hinricht** [versatiles-org/versatiles-rs#67]
I successfully converted the mbtiles src file from #65 using versatiles 0.6.7 to a versatiles file (`versatiles -v convert fahrradunfälle.mbtiles fahrradunfälle.versatiles`).

Then I started versatiles with: 

    docker run --detach --name versatiles --rm -p 8080:8080 -v /home/varac/ndr/versatiles/test/data/:/data docker.io/versatiles/versatiles-frontend:latest-alpine versatiles serve -s /app/frontend.br.tar -i 0.0.0.0 /data/fahrradunfälle.versatiles

The container logs show:

    /tiles/fahrradunfälle/*         <-  /data/fahrradunfälle.versatiles
    server starts listening on 0.0.0.0:8080

But the frontend only shows a blank space, no matter where I zoom:

![image](https://github.com/versatiles-org/versatiles-rs/assets/120004353/6b7d14e5-b933-44a2-a57e-29e3fe6801c5)

**Comment by MichaelKreil** [comment]
The frontend is currently only for Shortbread vector tiles. I have not implemented PNG tiles yet.
Hopefully I can add PNG support this week.
https://github.com/versatiles-org/versatiles-frontend/issues/19

**Comment by hinricht** [comment]
Is there an easy way to convert (verstailes/mbtiles) files containing PNG into ones that contain shortbread meanwhile ?
If not, totally fine then I'll wait for ersatiles-org/versatiles-frontend#19.

**Comment by MichaelKreil** [comment]
There is no good way to convert png tiles to vector tiles.
But I will hurry to update the frontend!

**Comment by hinricht** [comment]
Thanks, no need to hurry!
