### ISSUE TITLE
Add more files to download.versatiles.org

### ISSUE THREAD

**Issue by hinricht** [versatiles-org/versatiles-rs#68]
The public bucket `gs://versatiles` holds more versatiles files than https://download.versatiles.org/, where only the whole planet file are accessible. 
To make it easier for beginners it would be great to host more regions (europe, germany i.e.) that you can grab faster.

**Comment by hinricht** [comment]
Oh I just found the [partial download docs](https://github.com/versatiles-org/versatiles-documentation/blob/main/guides/download_tiles.md#partial-download) which kind of obsoletes this request :)

**Comment by MichaelKreil** [comment]
Also, we use this bucket for tile creation, not for public download, because Google traffic is quite expensive. (5€ per planet download)
