### ISSUE TITLE
mbtiles: ignore missing json

### ISSUE THREAD

**Issue by yetzt** [versatiles-org/versatiles-rs#72]
> `Error: Error { msg: "'json' is not defined in table 'metadata'" }`

mbtiles containers with raster tiles don't have a vector tile specification and therefore no `json` record in the metadata table. a missing vector tile specification should not halt the program when converting from mbtiles to other formats.

**Comment by MichaelKreil** [comment]
did you use the latest version?
```bash
versatiles -V
```

`versatiles 0.6.12`

**Comment by yetzt** [comment]
sorry, i still used `v0.5.5` when testing m)
