### ISSUE TITLE
feature request: file sytem "container"

### ISSUE THREAD

**Issue by yetzt** [versatiles-org/versatiles-rs#73]
reading tiles from and writing tiles to the file system should be possible. when having a huge tileset on the file system, creating an intermediate tar or mbtiles can be tedious.

**Comment by MichaelKreil** [comment]
Implemented: 1f5662e10944d63986561819356dbc3a5fa7dd4a, a5a0632271b80ddb6a2b759f872d49daf5ec7f90, b2a6809fa8e3e6e803d7c0b6ec9363c5ace92ac4
released: [v0.7.0](https://github.com/versatiles-org/versatiles-rs/releases/tag/v0.7.0)
