### ISSUE TITLE
ARM Windows Install fails 

### ISSUE THREAD

**Issue by yetzt** [versatiles-org/versatiles-rs#75]
I was asked to assist someone who wanted to run the versatiles tool on Windows. To test it out i installed Windows 11 ARM on Qemu. When running `cargo install versatiles`, `ring v0.17.8` fails to build. I don't know if there is something we can do about it, if this is a bug upstream or if i am missing something in my setup.

![Screenshot](https://github.com/versatiles-org/versatiles-rs/assets/152031/d80e0610-9355-467a-a531-e369434f3f43)

**Comment by MichaelKreil** [comment]
See also #31 
I never tested it under Windows since I don't have any Windows machines and compiling in a VM is a pain in the asymmetric photon. Do you have a Windows Notebook?

**Comment by yetzt** [comment]
nope sorry. i might have an ols windows install on my hackintosh, i will try to test it in the next few days

**Comment by MichaelKreil** [comment]
Thanks to [great support](https://github.com/versatiles-org/versatiles-rs/pull/103), VersaTiles now runs on Windows.
I'm closing this issue, but can you check that it compiles on Windows+ARM if you have time?
